### ISSUE TITLE
Add call to return total amount of boxes (spent and unspent) an address has

### ISSUE THREAD

**Issue by mgpai22** [capt-nemo429/ergo-graphql#29]
This will allow programs to easily scan addresses for updates by using amount of boxes as a parameter. The problem is that since APIs only return around 50 or 500 boxes at most  per call, we can't get box amount by getting the length of all boxes returned.

**Comment by capt-nemo429** [comment]
@SepehrGanji maybe we can change #28 and add `boxesCount` along side of `used`. For now both can use the same query as source. If `boxesCount` is selected it will return the all boxes that belongs to a given address, if `used` is selected you can you can just check if boxes count is greater than 0.

The advantage of this is that you can make just one query for all requested addresses at once.
