### ISSUE TITLE
Mempool: input boxes and proofBytes can sometimes return null 

### ISSUE THREAD

**Issue by pulsarz** [capt-nemo429/ergo-graphql#60]
When we use the following query as example, we can sometimes get an empty box in an input or get null proofBytes.

`query Transactions {
  mempool {
    transactions {
      transactionId
      size
      timestamp
      inputs {
        box {
          boxId
          value
          address
        }
        proofBytes
      }
    }
  }
}`
![image](https://user-images.githubusercontent.com/110669/194577743-e8d51768-79f9-4db0-a274-3a82e6314423.png)
![image](https://user-images.githubusercontent.com/110669/194577838-cd053a1f-5224-4a47-bf61-fabed2334d9f.png)

**Comment by capt-nemo429** [comment]
Issue identified, but not quick solution. So it will be solved for v0.4.1.

It happens when a transaction is using unconfirmed outputs as inputs. Current implementation only looks at confirmed inputs.
